# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html
Resources:
  SmorganEC2:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-03368e982f317ae48
      InstanceType: t2.micro
      UserData:
        Fn::Base64:
          !Sub | 
            # !/bin/bash
            yum update -y
            yum install -y nginx
            systemctl start nginx.service
            systemctl enable nginx.service
